batch_size: 256
clip_gradient_norm: 1
clip_targets_to_zero:
  - QObs(mm/d)
# - streamflow
data_dir: ./data/CAMELS_US #./data
dataset: camels_us #generic
device: cuda:0
forcings: daymet
dynamic_inputs:
  - prcp(mm/day)_daymet
  - srad(W/m2)_daymet
  - tmax(C)_daymet
  - tmin(C)_daymet
  - vp(Pa)_daymet
# - total_precipitation_sum
# - temperature_2m_max
# - temperature_2m_min
# - surface_net_solar_radiation_mean
# - surface_pressure_mean
# # - dewpoint_temperature_2m_mean
# # - surface_net_thermal_radiation_mean
# static_attributes:
# - p_mean
# - pet_mean_FAO_PM
# - aridity_FAO_PM
# # - seasonality_ERA5_LAND
# # - frac_snow
# - high_prec_freq
# - high_prec_dur
# - low_prec_freq
# - low_prec_dur
# - ele_mt_sav
# - slp_dg_sav
# - area
# # - for_pc_sse
# # - swc_pc_syr
# - snd_pc_sav
# # - slt_pc_sav
# - cly_pc_sav
# # - soc_th_sav
# # - glc_cl_smj
# - gwt_cm_sav
# - ero_kh_sav
# # - lit_cl_smj
epochs: 30
experiment_name: 10_basins_h128_do0.4_seq_length365_30epochs
head: regression
hidden_size: 128
initial_forget_bias: 3
# learning_rate:
#   0: 1e-4
#   10: 5e-5
#   20: 1e-5
learning_rate:
    0: 1e-3
    1: 5e-4
log_interval: 5
log_n_figures: 3
log_tensorboard: true
loss: NSE
metrics:
- NSE
- KGE
- Alpha-NSE
- Beta-NSE
- Pearson-r
- RMSE
model: cudalstm
num_workers: 8
optimizer: Adam
output_activation: linear
output_dropout: 0.4
predict_last_n: 1
run_dir: ./runs
save_validation_results: true
save_weights_every: 1
seed: 123
seq_length: 365
target_variables:
  - QObs(mm/d)
# - streamflow
test_basin_file: basins.txt
test_end_date: 31/08/2009
test_start_date: 01/09/2005
train_basin_file: basins.txt
train_dir: ./runs/test_run
train_end_date: 31/08/2001
train_start_date: 01/09/1989
validate_every: 1
validation_basin_file: basins.txt
validation_end_date: 31/08/2005
validation_start_date: 01/09/2001

verbose: 0
