name: Connect to Azure VPC
# https://docs.github.com/en/actions/how-tos/secure-your-work/security-harden-deployments/oidc-in-azure
on:
  workflow_dispatch:
    inputs:
      runner_type:
        description: 'Select the runner type'
        required: true
        default: 'ubuntu-2cpu-x64'
        type: choice
        options:
          - ubuntu-2cpu-x64
          - ubuntu-2cpu-arm
          - ubuntu-4cpu-arm

permissions:
  id-token: write
  contents: read
jobs:
  download:
    environment: AIForGood
    runs-on: ${{ github.event.inputs.runner_type }}
    steps:
      - name: Report Runner Specs
        run: |
          curl -H Metadata:true "http://169.254.169.254/metadata/instance?api-version=2017-12-01"
          lscpu
          free -h
          df -h

      - name: AZ CLI login
        uses: azure/login@v2.3.0
        with:
          # NOTE: allow-no-subscripts needed if only giving scoped permissions to specific container
          allow-no-subscriptions: true
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Test download from Azure Blob Storage
        run: |
          az storage blob download \
              --auth-mode login \
              --account-name dshydro\
              --container-name accelerator2025 \
              --name README.md \
              --file /tmp/README.md

      - name: Test mount Azure File Share
        env:
          AZURE_STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
        run: |
          mkdir /tmp/data
          sudo mount -t cifs //dshydro.file.core.windows.net/neurohydro /tmp/data -o vers=3.0,username=dshydro,password=$AZURE_STORAGE_ACCOUNT_KEY,dir_mode=0777,file_mode=0777,serverino

      - name: Test read/write data
        run: |
          ls -tlrh /tmp/data
          echo "hello from github actions" > /tmp/data/hello.txt
