name: NeuralHydrology Tutorial GPU

on:
  workflow_dispatch:

jobs:
  run-tutorial-gpu:
    # Cancel if runs take longer than 2 hours
    timeout-minutes: 120
    runs-on: T4GPU

    steps:
      - uses: actions/checkout@v6

      - name: Report Runner Specs
        run: |
          curl -H Metadata:true "http://169.254.169.254/metadata/instance?api-version=2017-12-01"
          lscpu
          free -h
          df -h

      - name: Report GPU specs
        run: |
          nvidia-smi

      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
            manifest-path: pyproject.toml
            cache: true
            frozen: true

      - name: Test GPU support
        run: |
            pixi run -e gpu python -c "import torch; print(torch.cuda.is_available())"

      - name: Cache Tutorial Data
        uses: actions/cache@v4
        with:
            path: basin_timeseries_v1p2_metForcing_obsFlow.zip
            key: ${{ runner.os }}-tutorial-data

     # Wget raises error code 1 if file already exists, so override
      - name: Download Tutorial Data
        run: |
            pixi run get-camels-data || true

      - name: Setup Tutorial Data
        run: |
            pixi run unzip-camels-data
            pixi run rename-camels-data

      - name: Run Training
        id: train
        run: |
            pixi run train-gpu
            OUTDIR=`ls runs/`
            echo "outdir=$OUTDIR" >> $GITHUB_OUTPUT

      - name: Run Evaluation
        run: |
            pixi run eval --run-dir ./runs/${{ steps.train.outputs.outdir }}

      - name: Visualize Results
        run: |
            pixi run visualize ./runs/${{ steps.train.outputs.outdir }}

      # note: names can't have slashes
      - name: Upload Results
        uses: actions/upload-artifact@v5
        with:
            name: ${{ steps.train.outputs.outdir }}
            path: ./runs/${{ steps.train.outputs.outdir }}
