name: TestGPU

on:
  workflow_dispatch:

jobs:
  test-gpu:
    timeout-minutes: 5
    runs-on: T4GPU

    steps:
      - uses: actions/checkout@v6

      - name: Report Runner Specs
        run: |
          curl -H Metadata:true "http://169.254.169.254/metadata/instance?api-version=2017-12-01"
          lscpu
          free -h
          df -h

      - name: Report GPU specs
        run: |
          nvidia-smi
